plugins: inline convert web fetchart embedart acousticbrainz beatport fromfilename bandcamp scrub

convert:
    auto: no

fetchart:
    auto: yes
    cautious: no
    cover_names: cover front art album folder
    sources: amazon itunes *

embedart:
    auto: yes
    ifempty: no

acousticbrainz:
    auto: yes

beatport:
    auto: yes

fromfilename:
   auto: yes

bandcamp:
   lyrics: yes
   art: yes
   split_artist_title: yes

scrub:
   auto: yes
